version: "3.9"
services:

  web:
    build: ./flask/
    image: flask_champs
    ports:
      - "5000:5000"
    depends_on:
      - mysql

  mysql:
    build: ./mysql/
    image: mysql_image
    restart: always
    ports:
      - "3307:3306"
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d/:ro
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
